// Generated by scripts/generate_packages.py from themes/THEMES.md. Do not edit by hand.

export const THEME_NAMES = [
  'blue-oval',
  'bubblegum',
  'commander-keen',
  'electric-lime',
  'flambeau',
  'flambeau-inverse',
  'green-acres',
  'hacker',
  'hawkeye',
  'lava',
  'merica',
  'neon',
  'red-barn',
  'retrowave',
] as const;

export type ThemeName = typeof THEME_NAMES[number];
