"""Deterministically build packages/{css,tkinter,flet,angular} from themes/THEMES.md.

themes/THEMES.md is the only source of truth. This script never invents or
adjusts a color value — it only reformats what's already in that file. Run
it after any change to themes/THEMES.md, then commit the regenerated output
under packages/.
"""
import re
from pathlib import Path

REPO_ROOT = Path(__file__).parent.parent
THEMES_MD = REPO_ROOT / "themes" / "THEMES.md"
PACKAGES_DIR = REPO_ROOT / "packages"

TOKEN_KEYS = [
    "topBarBg", "topBarHover", "text", "bg", "bgHover",
    "primaryAction", "primaryActionHover", "primaryActionText",
    "accentGreen", "accentRed", "accentBlue",
]


def slugify(name: str) -> str:
    return name.lower().replace(" ", "-")


def rgb_to_hex(value: str) -> str:
    if value == "null":
        return None
    match = re.match(r"rgb\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*\)", value)
    if not match:
        raise ValueError(f"Invalid RGB value: {value!r}")
    r, g, b = (int(match.group(i)) for i in (1, 2, 3))
    return f"#{r:02x}{g:02x}{b:02x}"


def parse_themes(themes_md: Path) -> list[dict]:
    text = themes_md.read_text()
    sections = re.split(r"\n### ", text)[1:]  # drop preamble before first theme
    themes = []
    for section in sections:
        name = section.split("\n", 1)[0].strip()
        desc_match = re.search(r"\n\n(.+?)\n\n```", section, re.S)
        description = desc_match.group(1).strip() if desc_match else ""

        block_match = re.search(r"```\n(.+?)\n```", section, re.S)
        if not block_match:
            raise ValueError(f"No token block found for theme {name!r}")
        colors = {}
        for line in block_match.group(1).splitlines():
            key, _, value = line.partition(":")
            colors[key.strip()] = value.strip()
        missing = [k for k in TOKEN_KEYS if k not in colors]
        if missing:
            raise ValueError(f"Theme {name!r} is missing tokens: {missing}")

        meta_match = re.search(
            r"inspiration:\s*(.+?)\s*·\s*author:\s*(.+?)\s*·\s*createdAt:\s*(.+)",
            section,
        )
        metadata = {}
        if meta_match:
            metadata = {
                "inspiration": meta_match.group(1).strip(),
                "author": meta_match.group(2).strip(),
                "createdAt": meta_match.group(3).strip(),
            }

        themes.append({
            "id": slugify(name),
            "name": name,
            "description": description,
            "colors": colors,
            "metadata": metadata,
        })
    return themes


def emit_css(themes: list[dict], out_dir: Path) -> None:
    lines = [
        "/* Generated by scripts/generate_packages.py from themes/THEMES.md. Do not edit by hand. */",
        "",
    ]
    for theme in themes:
        c = theme["colors"]
        lines.append(f"body.{theme['id']}-theme {{")
        lines.append(f"    --color-top-bar-bg: {c['topBarBg']};")
        lines.append(f"    --color-top-bar-hover: {c['topBarHover']};")
        lines.append(f"    --color-text: {c['text']};")
        lines.append(f"    --color-bg: {c['bg']};")
        lines.append(f"    --color-bg-hover: {c['bgHover']};")
        lines.append(f"    --color-primary-action: {c['primaryAction']};")
        lines.append(f"    --color-primary-action-hover: {c['primaryActionHover']};")
        if c["primaryActionText"] != "null":
            lines.append(f"    --color-primary-action-text: {c['primaryActionText']};")
        lines.append(f"    --color-accent-green: {c['accentGreen']};")
        lines.append(f"    --color-accent-red: {c['accentRed']};")
        lines.append(f"    --color-accent-blue: {c['accentBlue']};")
        lines.append("}")
        lines.append("")

    (out_dir / "themes.css").write_text("\n".join(lines))


def emit_tkinter(themes: list[dict], out_dir: Path) -> None:
    pkg_dir = out_dir / "visual_assault_tkinter"
    pkg_dir.mkdir(parents=True, exist_ok=True)

    lines = [
        '"""Generated by scripts/generate_packages.py from themes/THEMES.md. Do not edit by hand."""',
        "",
        "THEMES = {",
    ]
    for theme in themes:
        c = theme["colors"]
        tkinter_id = theme["id"].replace("-", "_")
        lines.append(f'    "{tkinter_id}": {{')
        lines.append(f'        "name": {theme["name"]!r},')
        lines.append(f'        "background": {rgb_to_hex(c["bg"])!r},')
        lines.append(f'        "backgroundHover": {rgb_to_hex(c["bgHover"])!r},')
        lines.append(f'        "foreground": {rgb_to_hex(c["text"])!r},')
        lines.append(f'        "topBarBackground": {rgb_to_hex(c["topBarBg"])!r},')
        lines.append(f'        "topBarHover": {rgb_to_hex(c["topBarHover"])!r},')
        lines.append(f'        "buttonBackground": {rgb_to_hex(c["primaryAction"])!r},')
        lines.append(f'        "buttonHover": {rgb_to_hex(c["primaryActionHover"])!r},')
        lines.append(f'        "accentGreen": {rgb_to_hex(c["accentGreen"])!r},')
        lines.append(f'        "accentRed": {rgb_to_hex(c["accentRed"])!r},')
        lines.append(f'        "accentBlue": {rgb_to_hex(c["accentBlue"])!r},')
        lines.append("    },")
    lines.append("}")
    lines.append("")

    (pkg_dir / "themes.py").write_text("\n".join(lines))

    init_path = pkg_dir / "__init__.py"
    if not init_path.exists():
        init_path.write_text(
            '"""Visual Assault themes for Tkinter/ttk apps."""\n'
            "from .themes import THEMES\n\n"
            '__all__ = ["THEMES"]\n'
        )


def emit_flet(themes: list[dict], out_dir: Path) -> None:
    pkg_dir = out_dir / "visual_assault_flet"
    pkg_dir.mkdir(parents=True, exist_ok=True)

    lines = [
        '"""Generated by scripts/generate_packages.py from themes/THEMES.md. Do not edit by hand.',
        "",
        "Plain color data only — no dependency on the `flet` package itself, so this",
        "stays correct across flet API versions. See README.md for how to wire a theme",
        "into flet.ColorScheme / flet.Theme in your app.",
        '"""',
        "",
        "THEMES = {",
    ]
    for theme in themes:
        c = theme["colors"]
        flet_id = theme["id"].replace("-", "_")
        lines.append(f'    "{flet_id}": {{')
        lines.append(f'        "name": {theme["name"]!r},')
        lines.append(f'        "background": {rgb_to_hex(c["bg"])!r},')
        lines.append(f'        "backgroundHover": {rgb_to_hex(c["bgHover"])!r},')
        lines.append(f'        "foreground": {rgb_to_hex(c["text"])!r},')
        lines.append(f'        "topBarBackground": {rgb_to_hex(c["topBarBg"])!r},')
        lines.append(f'        "topBarHover": {rgb_to_hex(c["topBarHover"])!r},')
        lines.append(f'        "primary": {rgb_to_hex(c["primaryAction"])!r},')
        lines.append(f'        "primaryHover": {rgb_to_hex(c["primaryActionHover"])!r},')
        lines.append(f'        "accentGreen": {rgb_to_hex(c["accentGreen"])!r},')
        lines.append(f'        "accentRed": {rgb_to_hex(c["accentRed"])!r},')
        lines.append(f'        "accentBlue": {rgb_to_hex(c["accentBlue"])!r},')
        lines.append("    },")
    lines.append("}")
    lines.append("")

    (pkg_dir / "themes.py").write_text("\n".join(lines))

    init_path = pkg_dir / "__init__.py"
    if not init_path.exists():
        init_path.write_text(
            '"""Visual Assault themes for Flet apps."""\n'
            "from .themes import THEMES\n\n"
            '__all__ = ["THEMES"]\n'
        )


def emit_angular(themes: list[dict], out_dir: Path) -> None:
    lines = [
        "// Generated by scripts/generate_packages.py from themes/THEMES.md. Do not edit by hand.",
        "",
    ]
    for theme in themes:
        c = theme["colors"]
        lines.append(f".theme-{theme['id']} {{")
        lines.append(f"  --color-top-bar-bg: {c['topBarBg']};")
        lines.append(f"  --color-top-bar-hover: {c['topBarHover']};")
        lines.append(f"  --color-text: {c['text']};")
        lines.append(f"  --color-bg: {c['bg']};")
        lines.append(f"  --color-bg-hover: {c['bgHover']};")
        lines.append(f"  --color-primary-action: {c['primaryAction']};")
        lines.append(f"  --color-primary-action-hover: {c['primaryActionHover']};")
        if c["primaryActionText"] != "null":
            lines.append(f"  --color-primary-action-text: {c['primaryActionText']};")
        lines.append(f"  --color-accent-green: {c['accentGreen']};")
        lines.append(f"  --color-accent-red: {c['accentRed']};")
        lines.append(f"  --color-accent-blue: {c['accentBlue']};")
        lines.append("}")
        lines.append("")

    (out_dir / "themes.scss").write_text("\n".join(lines))

    ts_lines = [
        "// Generated by scripts/generate_packages.py from themes/THEMES.md. Do not edit by hand.",
        "",
        "export const THEME_NAMES = [",
    ]
    for theme in themes:
        ts_lines.append(f"  '{theme['id']}',")
    ts_lines.append("] as const;")
    ts_lines.append("")
    ts_lines.append("export type ThemeName = typeof THEME_NAMES[number];")
    ts_lines.append("")

    (out_dir / "theme-names.ts").write_text("\n".join(ts_lines))


def main() -> None:
    themes = parse_themes(THEMES_MD)

    css_dir = PACKAGES_DIR / "css"
    tkinter_dir = PACKAGES_DIR / "tkinter"
    flet_dir = PACKAGES_DIR / "flet"
    angular_dir = PACKAGES_DIR / "angular"
    for d in (css_dir, tkinter_dir, flet_dir, angular_dir):
        d.mkdir(parents=True, exist_ok=True)

    emit_css(themes, css_dir)
    emit_tkinter(themes, tkinter_dir)
    emit_flet(themes, flet_dir)
    emit_angular(themes, angular_dir)

    print(f"Generated {len(themes)} themes into packages/{{css,tkinter,flet,angular}}")


if __name__ == "__main__":
    main()
